language: android

jdk:
  - oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository

before_install:
  - chmod +x gradlew
  - export CI=true

script:
  - ./gradlew clean build connectedCheck

sudo: false

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

branches:
  only:
    - master
    - dev